In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import os
os.chdir('C:\\Users\Tony\Dropbox\Research\Dataset')

In [18]:
# Read csv
files_lst = ['Site10_BayView_Fifteen.csv','Site11_Baisley_Park_Fifteen.csv','Site12_East_River_Fifteen.csv',
             'Site2_Queensborough_Community_College_Fifteen.csv','Site3_Ronald_Edmonds_Learning_Center_Fifteen.csv',
             'Site6_Dyckman_Houses_Fifteen.csv',
             'Site8_Polo_Ground_Fifteen.csv','Site9_Far_Rockaway_Fifteen.csv']

df_ls = []

for f in files_lst:
    df = pd.read_csv(f, skiprows=[1,2])
    df.drop(df.columns[0], axis=1, inplace = True)
    df.drop('RECORD', axis=1, inplace = True)
    df_ls.append(df)

In [19]:
df_ls[2]

,TIMESTAMP,VWC,T,P,VWC_2,T_2,P_2,VWC_3,T_3,P_3,VWC_4,T_4,P_4,AirTF,RH,Rainfall_Tot,Snowfall_Tot
0,2017-04-14 09:30:00,0.0000,67.86050,1.0351,0.0000,67.77176,1.0506,0,67.39268,1.0000,0.0000,68.00810,1.0000,-5.494484,35.01986,0.0,0.0
1,2017-04-14 09:45:00,0.0000,67.82594,1.0399,0.0000,67.74710,1.0549,0,67.43210,1.0000,0.0000,67.85546,1.0000,-3.796677,36.12487,0.0,0.0
2,2017-04-14 10:00:00,0.0000,67.70282,1.0341,0.0000,67.64864,1.0586,0,67.41230,1.0000,0.0000,67.80614,1.0000,-3.821407,36.12793,0.0,0.0
3,2017-04-14 10:15:00,0.0000,67.62901,1.0336,0.0000,67.43210,1.0577,0,67.29422,1.0000,0.0000,67.83584,1.0000,-4.010963,35.92035,0.0,0.0
4,2017-04-14 10:30:00,0.0000,67.52552,1.0346,0.0000,67.34336,1.0558,0,67.37288,1.0000,0.0000,67.88012,1.0000,-4.230743,35.81657,0.0,0.0
5,2017-04-14 10:45:00,0.0000,67.49600,1.0379,0.0000,67.35326,1.0553,0,67.34336,1.0000,0.0000,67.89973,1.0000,-4.359863,35.74483,0.0,0.0
6,2017-04-14 11:00:00,0.0000,67.52552,1.0355,0.0000,67.38278,1.0558,0,67.41716,1.0000,0.0000,67.84070,1.0000,-4.590633,35.53726,0.0,0.0
7,2017-04-14 11:15:00,0.0000,67.50590,1.0355,0.0000,67.38278,1.0544,0,67.42220,1.0000,0.0000,67.86050,1.0000,-4.697777,35.41516,0.0,0.0
8,2017-04-14 11:30:00,0.0000,67.54028,1.0370,0.0000,67.35812,1.0563,0,67.35812,1.0000,0.0000,67.89001,1.0000,-4.810417,35.35411,0.0,0.0
9,2017-04-14 11:45:00,0.0000,67.56494,1.0341,0.0000,67.34822,1.0553,0,67.39754,1.0000,0.0000,67.89488,1.0000,-4.802177,35.34954,0.0,0.0
10,2017-04-14 12:00:00,0.0000,67.60922,1.0355,0.0000,67.37288,1.0553,0,67.38763,1.0000,0.0000,67.91450,1.0000,-4.967010,35.23964,0.0,0.0
11,2017-04-14 12:15:00,0.0000,67.61913,1.0370,0.0000,67.44685,1.0577,0,67.46162,1.0000,0.0000,67.92926,1.0000,-4.934044,35.53879,0.0,0.0
12,2017-04-14 12:30:00,0.0000,67.63388,1.0331,0.0000,67.46162,1.0530,0,67.44685,1.0000,0.0000,67.87508,1.0000,-5.060417,35.49606,0.0,0.0
13,2017-04-14 12:45:00,0.0000,67.56494,1.0360,0.0000,67.43210,1.0520,0,67.41716,1.0000,0.0000,67.93916,1.0000,-5.129093,35.47316,0.0,0.0
14,2017-04-14 13:00:00,0.0000,67.54532,1.0355,0.0000,67.45172,1.0535,0,67.45657,1.0000,0.0000,67.95392,1.0000,-5.200527,35.44874,0.0,0.0
15,2017-04-14 13:15:00,0.0000,67.59932,1.0355,0.0000,67.49113,1.0567,0,67.47134,1.0000,0.0000,67.96867,1.0000,-5.181293,35.41059,0.0,0.0
16,2017-04-14 13:30:00,0.0000,67.63388,1.0351,0.0000,67.52552,1.0586,0,67.47134,1.0000,0.0000,67.93916,1.0000,-5.299427,35.31901,0.0,0.0
17,2017-04-14 13:45:00,0.0000,67.56494,1.0370,0.0000,67.52552,1.0553,0,67.47638,1.0000,0.0000,67.95392,1.0000,-5.244484,35.30527,0.0,0.0
18,2017-04-14 14:00:00,0.0000,67.64378,1.0341,0.0000,67.55504,1.0567,0,67.47134,1.0000,0.0000,67.92440,1.0000,-5.337891,35.28391,0.0,0.0
19,2017-04-14 14:15:00,0.0000,67.68320,1.0375,0.0000,67.63873,1.0544,0,67.49600,1.0000,0.0000,67.97372,1.0000,-5.381847,35.29001,0.0,0.0
20,2017-04-14 14:30:00,0.0000,67.69795,1.0375,0.0000,67.61913,1.0586,0,67.55504,1.0000,0.0000,67.97372,1.0000,-5.510967,35.16180,0.0,0.0
21,2017-04-14 14:45:00,0.0000,67.71758,1.0351,0.0000,67.64378,1.0530,0,67.57484,1.0000,0.0000,67.96867,1.0000,-5.609867,35.03054,0.0,0.0
22,2017-04-14 15:00:00,0.0000,67.77662,1.0346,0.0000,67.64378,1.0521,0,67.53542,1.0000,0.0000,67.99334,1.0000,-5.667561,35.04123,0.0,0.0
23,2017-04-14 15:15:00,0.0000,67.77176,1.0355,0.0000,67.69795,1.0521,0,67.51580,1.0000,0.0000,68.03762,1.0000,-5.623604,35.03207,0.0,0.0
24,2017-04-14 15:30:00,0.0000,67.77662,1.0327,0.0000,67.67312,1.0525,0,67.53056,1.0000,0.0000,67.95392,1.0000,-5.675800,35.00307,0.0,0.0
25,2017-04-14 15:45:00,0.0000,67.71758,1.0375,0.0000,67.71758,1.0558,0,67.53542,1.0000,0.0000,67.99838,1.0000,-5.711517,34.96339,0.0,0.0
26,2017-04-14 16:00:00,0.0000,67.76672,1.0331,0.0000,67.65350,1.0572,0,67.56007,1.0000,0.0000,67.96867,1.0000,-5.771954,34.96797,0.0,0.0
27,2017-04-14 16:15:00,0.0000,67.75700,1.0355,0.0000,67.69795,1.0558,0,67.50104,1.0000,0.0000,67.99838,1.0000,-5.747227,34.94508,0.0,0.0
28,2017-04-14 16:30:00,0.0000,67.72748,1.0336,0.0000,67.69292,1.0539,0,67.48124,1.0000,0.0000,67.95392,1.0000,-5.722507,34.99697,0.0,0.0
29,2017-04-14 16:45:00,0.0000,67.69292,1.0365,0.0000,67.67816,1.0525,0,67.44182,1.0000,0.0000,67.96867,1.0000,-5.722507,35.00307,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31332,2018-07-20 08:00:00,0.2456,73.13882,13.1484,0.2232,73.34204,11.8657,0.2545,73.24286,13.6751,0.2154,73.24286,11.4342,52.189620,68.05865,0.0,0.0
31333,2018-07-20 08:15:00,0.2449,73.46120,13.1045,0.2225,73.42142,11.8249,0.2544,73.83344,13.6721,0.2154,73.37192,11.4328,76.810520,67.93503,0.0,0.0
31334,2018-07-20 08:30:00,0.2456,73.80356,13.1448,0.2225,73.57532,11.8236,0.2544,74.38010,13.6710,0.2154,73.52563,11.4327,77.016560,70.30988,0.0,0.0
31335,2018-07-20 08:45:00,0.2456,74.06186,13.1460,0.2225,73.76882,11.8247,0.2537,74.78798,13.6279,0.2154,73.64966,11.4337,76.247330,67.36573,0.0,0.0
31336,2018-07-20 09:00:00,0.2455,74.25068,13.1439,0.2225,73.93280,11.8252,0.2536,75.10676,13.6253,0.2146,73.88798,11.3929,77.566000,68.76836,0.0,0.0
31337,2018-07-20 09:15:00,0.2455,74.59880,13.1429,0.2225,74.09174,11.8238,0.2529,75.35084,13.5831,0.2146,74.05196,11.3927,78.423160,67.84803,0.0,0.0
31338,2018-07-20 09:30:00,0.2448,75.09668,13.0988,0.2218,74.29046,11.7845,0.2536,75.86978,13.6263,0.2146,74.27570,11.3923,79.752830,62.41304,0.0,0.0
31339,2018-07-20 09:45:00,0.2448,75.77492,13.0971,0.2217,74.59377,11.7830,0.2529,76.39934,13.5822,0.2146,74.44472,11.3920,79.511080,64.20028,0.0,0.0
31340,2018-07-20 10:00:00,0.2440,76.41932,13.0552,0.2217,74.96726,11.7816,0.2522,76.83458,13.5367,0.2139,74.66360,11.3524,79.783040,64.18807,0.0,0.0
31341,2018-07-20 10:15:00,0.2433,77.14021,13.0126,0.2210,75.37082,11.7407,0.2515,77.18036,13.4956,0.2139,74.93738,11.3517,81.445140,61.06536,0.0,0.0
31342,2018-07-20 10:30:00,0.2433,77.70218,13.0092,0.2210,75.78986,11.7411,0.2508,77.53154,13.4526,0.2139,75.14655,11.3502,81.791290,54.85046,0.0,0.0
31343,2018-07-20 10:45:00,0.2425,78.34064,12.9672,0.2202,76.18945,11.7004,0.25,77.93330,13.4093,0.2132,75.39080,11.3129,82.186890,54.96341,0.0,0.0
31344,2018-07-20 11:00:00,0.2425,78.66302,12.9672,0.2202,76.63441,11.6984,0.2507,77.87300,13.4497,0.2132,75.57530,11.3119,82.170410,49.14991,0.0,0.0
31345,2018-07-20 11:15:00,0.2425,79.26332,12.9641,0.2195,76.93484,11.6591,0.25,77.94842,13.4082,0.2125,75.73982,11.2745,81.958870,50.63496,0.0,0.0
31346,2018-07-20 11:30:00,0.2418,79.07144,12.9227,0.2195,77.31572,11.6586,0.2493,77.55170,13.3679,0.2124,75.85466,11.2718,81.837980,47.12152,0.0,0.0
31347,2018-07-20 11:45:00,0.2411,79.82474,12.8825,0.2188,77.54666,11.6183,0.2486,78.08918,13.3256,0.2124,75.96950,11.2717,83.859950,46.05314,0.0,0.0
31348,2018-07-20 12:00:00,0.2404,79.72844,12.8410,0.2187,77.83790,11.6173,0.2479,77.80766,13.2833,0.2117,76.16444,11.2322,82.618200,41.50186,0.0,0.0
31349,2018-07-20 12:15:00,0.2397,79.50596,12.8010,0.2188,78.01376,11.6187,0.2479,77.69210,13.2829,0.2117,76.22942,11.2308,81.802280,46.64991,0.0,0.0
31350,2018-07-20 12:30:00,0.2404,79.19780,12.8428,0.2180,77.96336,11.5787,0.2472,77.75240,13.2427,0.2117,76.26938,11.2307,83.123710,48.67372,0.0,0.0
31351,2018-07-20 12:45:00,0.2397,79.64761,12.8017,0.2180,78.06398,11.5778,0.2472,78.79910,13.2397,0.2110,76.46432,11.1928,83.601720,40.73568,0.0,0.0
31352,2018-07-20 13:00:00,0.2390,79.66273,12.7628,0.2173,78.30050,11.5396,0.2457,79.24820,13.1550,0.2102,76.75448,11.1532,82.612720,46.94295,0.0,0.0
31353,2018-07-20 13:15:00,0.2383,79.44530,12.7214,0.2173,78.27026,11.5389,0.245,79.65770,13.1118,0.2102,76.98488,11.1525,82.376450,41.60564,0.0,0.0
31354,2018-07-20 13:30:00,0.2383,79.52108,12.7222,0.2166,78.28033,11.5000,0.245,80.12354,13.1116,0.2095,77.31068,11.1134,83.500080,46.83459,0.0,0.0
31355,2018-07-20 13:45:00,0.2369,80.02724,12.6385,0.2166,78.55717,11.4986,0.2443,80.20976,13.0685,0.2095,77.53658,11.1137,80.741840,46.58276,0.0,0.0
31356,2018-07-20 14:00:00,0.2376,80.06773,12.6803,0.2159,78.59750,11.4608,0.2436,80.33144,13.0270,0.2087,77.71227,11.0737,82.763810,45.10381,0.0,0.0
31357,2018-07-20 14:15:00,0.2368,80.78846,12.6368,0.2159,78.80414,11.4614,0.2421,80.86982,12.9431,0.2087,77.86796,11.0731,81.486340,45.10839,0.0,0.0
31358,2018-07-20 14:30:00,0.2361,81.05288,12.5965,0.2152,79.18772,11.4218,0.2422,80.00186,12.9449,0.2087,78.02383,11.0726,80.758320,41.68196,0.0,0.0
31359,2018-07-20 14:45:00,0.2354,80.70206,12.5557,0.2152,79.31390,11.4218,0.2415,79.40984,12.9065,0.2080,78.14444,11.0338,81.406670,42.86480,0.0,0.0
31360,2018-07-20 15:00:00,0.2348,80.04758,12.5179,0.2151,79.37456,11.4196,0.2415,78.55214,12.9066,0.2080,78.06902,11.0357,80.002820,42.05589,0.0,0.0
31361,2018-07-20 15:15:00,0.2341,79.45538,12.4772,0.2144,79.16234,11.3809,0.2415,78.04886,12.9086,0.2080,77.85284,11.0339,81.104480,41.13708,0.0,0.0

In [20]:
num_col = ['VWC', 'T', 'P', 'VWC_2', 'T_2', 'P_2', 'VWC_3',
      'T_3', 'P_3', 'VWC_4', 'T_4', 'P_4', 'AirTF', 'RH', 'Rainfall_Tot',
      'Snowfall_Tot']

df_ls_scaled = []

for i, df in enumerate(df_ls):
    temp_df = df.copy()

    # 'NAN' -> np.nan
    temp_df.replace('NAN', np.nan, inplace = True)
    
    # replace inf -> nan
    temp_df.replace(np.inf, np.nan, inplace = True)

    # drop na | drop np.nan
    temp_df.fillna(0, inplace = True)


    temp_df_scaled = temp_df.copy()

    # temp_df = temp_df[['RECORD', 'VWC', 'T', 'P','VWC_2', 'T_2','P_2', 'VWC_3']].copy()

    # scalling 
    min_max_scaler = preprocessing.MinMaxScaler()
    
    try:
        scaled_data = min_max_scaler.fit_transform(temp_df_scaled[num_col])
    except:
        print(i)
        
    temp_df_scaled[num_col] = scaled_data
    df_ls_scaled.append(temp_df_scaled)

In [21]:
# Extract time stamp for finding common set
time_stamp_df = [df[['TIMESTAMP']] for df in df_ls]

ts_union = time_stamp_df[0]
for i in range(1,len(time_stamp_df)):
    ts_union = pd.merge(ts_union, time_stamp_df[i], how='inner', on = ['TIMESTAMP'])
    
ts_union_lst = ts_union['TIMESTAMP'].values

ts_union.head()

             TIMESTAMP
0  2018-02-13 14:00:00
1  2018-02-13 14:15:00
2  2018-02-13 14:30:00
3  2018-02-13 14:45:00
4  2018-02-13 15:00:00

In [25]:
# Manipulating one df
for i, f in enumerate(files_lst):
    
    filename = '(modifed) ' + f
    
    temp_df = df_ls_scaled[i]
    temp_df = temp_df[temp_df['TIMESTAMP'].isin(ts_union_lst)]

    temp_df['TIMESTAMP'] = pd.to_datetime(temp_df['TIMESTAMP'])

    temp_df.head()

    temp_df = temp_df.groupby(pd.DatetimeIndex(temp_df['TIMESTAMP']).normalize()).mean().reset_index()

    temp_df.sort_values(by = 'TIMESTAMP', inplace = True)

    temp_df.to_csv(filename, index=False)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [24]:
len(files_lst)

8