In [2]:
!kaggle datasets download -d usfundamentals/us-stocks-fundamentals

/bin/sh: kaggle: command not found

In [3]:
ls

DSE1020-DataStructures-9-12-19-prep.ipynb*
DSE1020-DataStructures-9-12-19-prep.pdf*
DSE1020-DataStructures-9-12-19.ipynb*
DSE1020-DataWrangling-BS-9-26-18-prep-Copy1.txt.ipynb*
DSE1020-DataWrangling-BS-9-26-18-prep.ipynb*
Data Wrangling--Web Scraping.ipynb*
Ng_MLY01_13.pdf*
Working with Missing Values.ipynb*
companies.csv*
companies.json*
indicators_by_company.csv*
notebook.tex*
us-stocks-fundamentals.zip*

In [32]:
import pandas as pd
import numpy as np

In [5]:
companies = pd.read_csv('companies.csv')
indicators = pd.read_csv('indicators_by_company.csv')

In [6]:
companies.head()

   company_id               name_latest names_previous
0     1000045    Nicholas Financial Inc            NaN
1     1000180              Sandisk Corp            NaN
2     1000209  Medallion Financial Corp            NaN
3     1000228          Henry Schein Inc            NaN
4     1000229     Core Laboratories N V            NaN

In [7]:
companies.shape

(12173, 3)

In [8]:
indicators.shape

(1907883, 9)

In [9]:
indicators.head()

,company_id,indicator_id,2010,2011,2012,2013,2014,2015,2016
0,1000045,AccountsPayableAndAccruedLiabilitiesCurrentAnd...,NaN,6612429.0,7405579.0,8924919.0,7841070.0,5839000.0,NaN
1,1000045,AccumulatedDepreciationDepletionAndAmortizatio...,NaN,NaN,2111343.0,2242703.0,2236449.0,2462000.0,NaN
2,1000045,AdjustmentForAmortization,NaN,NaN,-11482251.0,-13490892.0,-13852305.0,-13811000.0,NaN
3,1000045,Assets,NaN,257236034.0,263835468.0,283429579.0,302528591.0,325309000.0,NaN
4,1000045,AssetsHeldForSaleAtCarryingValue,NaN,1373001.0,1203664.0,1696330.0,NaN,NaN,NaN

In [10]:
indicators['indicator_id'].unique()

array(['AccountsPayableAndAccruedLiabilitiesCurrentAndNoncurrent',
       'AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment',
       'AdjustmentForAmortization', ..., 'ProceedsFromSaleOfLand',
       'CashDividendsPaidToParentCompanyBy50PercentOrLessOwnedPersons',
       'LiabilitiesSubjectToCompromiseRetainedObligationOfDivestedBusinesses'],
      dtype=object)

In [11]:
indicators['indicator_id'].unique().size

8529

In [12]:
ind2015 = indicators[['company_id','indicator_id','2015']]
ind2015.head()

   company_id                                       indicator_id         2015
0     1000045  AccountsPayableAndAccruedLiabilitiesCurrentAnd...    5839000.0
1     1000045  AccumulatedDepreciationDepletionAndAmortizatio...    2462000.0
2     1000045                          AdjustmentForAmortization  -13811000.0
3     1000045                                             Assets  325309000.0
4     1000045                   AssetsHeldForSaleAtCarryingValue          NaN

In [13]:
ind2015 = ind2015.dropna() 
ind2015.head()

   company_id                                       indicator_id         2015
0     1000045  AccountsPayableAndAccruedLiabilitiesCurrentAnd...    5839000.0
1     1000045  AccumulatedDepreciationDepletionAndAmortizatio...    2462000.0
2     1000045                          AdjustmentForAmortization  -13811000.0
3     1000045                                             Assets  325309000.0
5     1000045  AssetsOfDisposalGroupIncludingDiscontinuedOper...    2148000.0

In [14]:
df_comp_count = ind2015.groupby(['indicator_id'])['company_id'].count()
df_comp_count.head()

indicator_id
AcceleratedShareRepurchaseProgramAdjustment               3
AcceleratedShareRepurchasesAdjustmentToRecordedAmount     1
AcceleratedShareRepurchasesFinalPricePaidPerShare        12
AcceleratedShareRepurchasesInitialPricePaidPerShare       1
AcceleratedShareRepurchasesSettlementPaymentOrReceipt     4
Name: company_id, dtype: int64

In [15]:
comp_sourted_count = df_comp_count.sort_values(ascending=False)
comp_sourted_count.head(25)

indicator_id
LiabilitiesAndStockholdersEquity                                            6012
Assets                                                                      5997
StockholdersEquity                                                          5503
RetainedEarningsAccumulatedDeficit                                          5500
NetIncomeLoss                                                               5492
CashAndCashEquivalentsAtCarryingValue                                       5490
CashAndCashEquivalentsPeriodIncreaseDecrease                                5151
CommonStockSharesAuthorized                                                 5114
CommonStockValue                                                            4916
CommonStockSharesIssued                                                     4901
PropertyPlantAndEquipmentNet                                                4808
CommonStockParOrStatedValuePerShare                                         4763
Liabilities                                                                 4659
IncomeTaxExpenseBenefit                                                     4614
AssetsCurrent                                                               4598
LiabilitiesCurrent                                                          4597
OperatingIncomeLoss                                                         4522
CommonStockSharesOutstanding                                                4519
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    4519
PropertyPlantAndEquipmentGross                                              4192
ShareBasedCompensation                                                      4096
OperatingLeasesFutureMinimumPaymentsDueInTwoYears                           3934
DeferredTaxAssetsValuationAllowance                                         3928
OperatingLeasesFutureMinimumPaymentsDueCurrent                              3925
InterestExpense                                                             3891
Name: company_id, dtype: int64

In [16]:
pop_ind = comp_sourted_count.head(20).index.tolist()
pop_ind

['LiabilitiesAndStockholdersEquity',
 'Assets',
 'StockholdersEquity',
 'RetainedEarningsAccumulatedDeficit',
 'NetIncomeLoss',
 'CashAndCashEquivalentsAtCarryingValue',
 'CashAndCashEquivalentsPeriodIncreaseDecrease',
 'CommonStockSharesAuthorized',
 'CommonStockValue',
 'CommonStockSharesIssued',
 'PropertyPlantAndEquipmentNet',
 'CommonStockParOrStatedValuePerShare',
 'Liabilities',
 'IncomeTaxExpenseBenefit',
 'AssetsCurrent',
 'LiabilitiesCurrent',
 'OperatingIncomeLoss',
 'CommonStockSharesOutstanding',
 'AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment',
 'PropertyPlantAndEquipmentGross']

In [17]:
pivot_df = indicators.pivot(index='company_id', columns='indicator_id', values='2015')

In [18]:
pivot_df.head()

indicator_id,AcceleratedShareRepurchaseProgramAdjustment,AcceleratedShareRepurchasesAdjustmentToRecordedAmount,AcceleratedShareRepurchasesFinalPricePaidPerShare,AcceleratedShareRepurchasesInitialPricePaidPerShare,AcceleratedShareRepurchasesSettlementPaymentOrReceipt,AccountsAndNotesReceivableNet,AccountsAndOtherReceivablesNetCurrent,AccountsNotesAndLoansReceivableNetCurrent,AccountsPayable,AccountsPayableAndAccruedLiabilities,...,WellServiceExpense,WellsInProcessOfDrilling,WithdrawalFromContractHoldersFunds,WorkersCompensationDiscountAmount,WorkersCompensationDiscountPercent,WorkersCompensationLiabilityCurrent,WorkersCompensationLiabilityCurrentAndNoncurrent,WorkersCompensationLiabilityNoncurrent,WriteOffOfDeferredDebtIssuanceCost,WriteOffOfInventory
company_id,,,,,,,,,,,,,,,,,,,,,
1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
pivot_df[pop_ind].head()

indicator_id,LiabilitiesAndStockholdersEquity,Assets,StockholdersEquity,RetainedEarningsAccumulatedDeficit,NetIncomeLoss,CashAndCashEquivalentsAtCarryingValue,CashAndCashEquivalentsPeriodIncreaseDecrease,CommonStockSharesAuthorized,CommonStockValue,CommonStockSharesIssued,PropertyPlantAndEquipmentNet,CommonStockParOrStatedValuePerShare,Liabilities,IncomeTaxExpenseBenefit,AssetsCurrent,LiabilitiesCurrent,OperatingIncomeLoss,CommonStockSharesOutstanding,AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment,PropertyPlantAndEquipmentGross
company_id,,,,,,,,,,,,,,,,,,,,
1750,1.442100e+09,1.442100e+09,NaN,6.816000e+08,4.770000e+07,3.120000e+07,-23500000.0,1.000000e+08,4.490000e+07,4.486770e+07,2.328000e+08,1.00,NaN,18800000.0,8.731000e+08,3.290000e+08,NaN,NaN,4.173000e+08,6.501000e+08
1800,4.124700e+10,4.124700e+10,2.121100e+10,2.575700e+10,4.423000e+09,5.001000e+09,938000000.0,2.400000e+09,1.273400e+10,1.702017e+09,5.730000e+09,NaN,NaN,577000000.0,1.415500e+10,9.186000e+09,2.867000e+09,NaN,6.653000e+09,1.238300e+10
1961,NaN,NaN,-5.141478e+06,NaN,-4.037365e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7.000570e+05,NaN,NaN,NaN
2034,5.407780e+08,5.407780e+08,3.044420e+08,1.948040e+08,3.476600e+07,6.682800e+07,32808000.0,7.500000e+07,2.960000e+05,2.959500e+07,1.004400e+07,0.01,236336000.0,19088000.0,3.526610e+08,9.890600e+07,5.802800e+07,29595000.0,1.066400e+07,2.070800e+07
2098,8.142137e+07,8.142137e+07,4.318356e+07,3.734040e+07,4.793525e+06,2.425891e+06,140231.0,8.000000e+06,1.187690e+07,4.751060e+06,7.401478e+06,2.50,38237805.0,1820872.0,5.963349e+07,1.193675e+07,7.347006e+06,NaN,8.687902e+06,1.608938e+07

In [20]:
pivot_df[pop_ind].shape

(9619, 20)

In [21]:
company_features_df = pivot_df[pop_ind].dropna()

In [22]:
company_features_df.head()

indicator_id,LiabilitiesAndStockholdersEquity,Assets,StockholdersEquity,RetainedEarningsAccumulatedDeficit,NetIncomeLoss,CashAndCashEquivalentsAtCarryingValue,CashAndCashEquivalentsPeriodIncreaseDecrease,CommonStockSharesAuthorized,CommonStockValue,CommonStockSharesIssued,PropertyPlantAndEquipmentNet,CommonStockParOrStatedValuePerShare,Liabilities,IncomeTaxExpenseBenefit,AssetsCurrent,LiabilitiesCurrent,OperatingIncomeLoss,CommonStockSharesOutstanding,AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment,PropertyPlantAndEquipmentGross
company_id,,,,,,,,,,,,,,,,,,,,
2034,5.407780e+08,5.407780e+08,3.044420e+08,1.948040e+08,3.476600e+07,6.682800e+07,32808000.0,75000000.0,296000.0,29595000.0,1.004400e+07,0.01,2.363360e+08,19088000.0,3.526610e+08,9.890600e+07,5.802800e+07,29595000.0,1.066400e+07,2.070800e+07
2178,2.432150e+08,2.432150e+08,1.525100e+08,1.403950e+08,-1.275000e+06,9.187700e+07,11693000.0,7500000.0,422000.0,4217596.0,5.971500e+07,0.10,9.070500e+07,-770000.0,1.765370e+08,8.019700e+07,-2.359000e+06,4217596.0,1.535210e+08,2.132360e+08
2969,1.743810e+10,1.743810e+10,7.249000e+09,1.058040e+10,1.277900e+09,2.064000e+08,-130200000.0,300000000.0,249400000.0,249455584.0,9.636900e+09,1.00,1.005700e+10,415900000.0,2.910800e+09,3.648100e+09,1.699100e+09,215359113.0,1.071770e+10,2.035460e+10
4127,3.719400e+09,3.719400e+09,3.159200e+09,1.469200e+09,7.983000e+08,1.043600e+09,237800000.0,525000000.0,47600000.0,219000000.0,8.264000e+08,0.25,5.602000e+08,225300000.0,1.914700e+09,4.639000e+08,1.023100e+09,190300000.0,7.590000e+08,1.585400e+09
6176,5.061560e+08,5.061560e+08,2.114230e+08,1.297420e+08,1.373000e+06,9.512200e+07,-1976000.0,20000000.0,10440000.0,10440000.0,1.469130e+08,1.00,2.947330e+08,2633000.0,2.196820e+08,8.133300e+07,5.047000e+06,10440000.0,1.805780e+08,3.274910e+08

In [23]:
company_features_df.isnull().any()

indicator_id
LiabilitiesAndStockholdersEquity                                            False
Assets                                                                      False
StockholdersEquity                                                          False
RetainedEarningsAccumulatedDeficit                                          False
NetIncomeLoss                                                               False
CashAndCashEquivalentsAtCarryingValue                                       False
CashAndCashEquivalentsPeriodIncreaseDecrease                                False
CommonStockSharesAuthorized                                                 False
CommonStockValue                                                            False
CommonStockSharesIssued                                                     False
PropertyPlantAndEquipmentNet                                                False
CommonStockParOrStatedValuePerShare                                         False
Liabilities                                                                 False
IncomeTaxExpenseBenefit                                                     False
AssetsCurrent                                                               False
LiabilitiesCurrent                                                          False
OperatingIncomeLoss                                                         False
CommonStockSharesOutstanding                                                False
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    False
PropertyPlantAndEquipmentGross                                              False
dtype: bool

In [24]:
company_features_df.shape

(948, 20)

In [25]:
small_data_table = pd.merge(companies[['company_id','name_latest']], company_features_df,
                            on='company_id')

In [26]:
small_data_table.head()

,company_id,name_latest,LiabilitiesAndStockholdersEquity,Assets,StockholdersEquity,RetainedEarningsAccumulatedDeficit,NetIncomeLoss,CashAndCashEquivalentsAtCarryingValue,CashAndCashEquivalentsPeriodIncreaseDecrease,CommonStockSharesAuthorized,...,PropertyPlantAndEquipmentNet,CommonStockParOrStatedValuePerShare,Liabilities,IncomeTaxExpenseBenefit,AssetsCurrent,LiabilitiesCurrent,OperatingIncomeLoss,CommonStockSharesOutstanding,AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment,PropertyPlantAndEquipmentGross
0,1000623,Schweitzer Mauduit International Inc,1.290000e+09,1.290000e+09,467900000.0,552600000.0,89700000.0,186500000.0,-103800000.0,100000000.0,...,308100000.0,0.10,822100000.0,21600000.0,444800000.0,143100000.0,103000000.0,30474149.0,354700000.0,662800000.0
1,1000694,Novavax Inc,3.860380e+08,3.860380e+08,292669000.0,-650030000.0,-156937000.0,93108000.0,60773000.0,600000000.0,...,32342000.0,0.01,93369000.0,0.0,287257000.0,76494000.0,-157236000.0,269971232.0,15817000.0,48159000.0
2,1001115,Geospace Technologies Corp,3.070460e+08,3.070460e+08,289624000.0,228278000.0,-32641000.0,22314000.0,-11043000.0,20000000.0,...,48709000.0,0.01,17422000.0,-17193000.0,205009000.0,13934000.0,-52555000.0,13147916.0,45196000.0,93905000.0
3,1001233,Sangamo Biosciences Inc,2.172350e+08,2.172350e+08,192439000.0,-369253000.0,-40703000.0,69482000.0,63452000.0,160000000.0,...,2916000.0,0.01,24796000.0,-5722000.0,212582000.0,20097000.0,-46856000.0,70354608.0,4846000.0,7762000.0
4,1001385,Northwest Pipe CO,2.593800e+08,2.593800e+08,217560000.0,101183000.0,-29388000.0,10309000.0,9782000.0,15000000.0,...,131848000.0,0.01,41820000.0,-11951000.0,115279000.0,21570000.0,-40210000.0,9564752.0,86451000.0,218299000.0

In [27]:
small_data_table['name_latest']

0          Schweitzer Mauduit International Inc
1                                   Novavax Inc
2                    Geospace Technologies Corp
3                       Sangamo Biosciences Inc
4                             Northwest Pipe CO
5                                  Tengasco Inc
6             Learning Tree International, Inc.
7                   Nuance Communications, Inc.
8                Entertainment Gaming Asia Inc.
9                   Universal Display Corp \PA\
10                             Landec Corp \CA\
11                            UGI Utilities Inc
12                                    Argan Inc
13                     Sierra Monitor Corp /CA/
14                        Coffee Holding CO Inc
15                      KVH Industries Inc \DE\
16             Streamline Health Solutions Inc.
17                           Union Pacific Corp
18           Brocade Communications Systems Inc
19                            Jakks Pacific Inc
20                         AIR Industries Group
21                        Siga Technologies Inc
22                                  Polycom Inc
23                                    Yahoo Inc
24                             Medivation, Inc.
25                           Sealed AIR Corp/De
26                 Factset Research Systems Inc
27                           Endologix Inc /DE/
28                              Pegasystems Inc
29                        Strayer Education Inc
                         ...
918                        Acacia Research Corp
919                    Speedway Motorsports Inc
920                         ACI Worldwide, Inc.
921              RCI Hospitality Holdings, Inc.
922                   National Instruments Corp
923                                  Ciena Corp
924                        Lockheed Martin Corp
925                            Trinet Group Inc
926                                   Pcm, Inc.
927                       Imageware Systems Inc
928        Ever-Glory International Group, Inc.
929    Westinghouse AIR Brake Technologies Corp
930                         Socket Mobile, Inc.
931                                  Cbiz, Inc.
932                             GSE Systems Inc
933                                  Cicero Inc
934                              Ixys Corp /DE/
935                                   Pool Corp
936                     Ballantyne Strong, Inc.
937              Windtree Therapeutics Inc /DE/
938           Take TWO Interactive Software Inc
939                   ALY Energy Services, Inc.
940                           Levi Strauss & CO
941               Diamond Offshore Drilling Inc
942                                    Cray Inc
943                              Tejon Ranch CO
944                                  Tennant CO
945                               Teradyne, Inc
946                              Trans LUX Corp
947                                Transcat Inc
Name: name_latest, Length: 948, dtype: object

In [28]:
small_data_table[small_data_table['name_latest'].str.contains('Yahoo Inc')]

,company_id,name_latest,LiabilitiesAndStockholdersEquity,Assets,StockholdersEquity,RetainedEarningsAccumulatedDeficit,NetIncomeLoss,CashAndCashEquivalentsAtCarryingValue,CashAndCashEquivalentsPeriodIncreaseDecrease,CommonStockSharesAuthorized,...,PropertyPlantAndEquipmentNet,CommonStockParOrStatedValuePerShare,Liabilities,IncomeTaxExpenseBenefit,AssetsCurrent,LiabilitiesCurrent,OperatingIncomeLoss,CommonStockSharesOutstanding,AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment,PropertyPlantAndEquipmentGross
23,1011006,Yahoo Inc,4.520397e+10,4.520397e+10,2.904354e+10,4.570807e+09,-4.359082e+09,1.631911e+09,-1.032187e+09,5.000000e+09,...,1.547323e+09,0.001,1.612455e+10,-89598000.0,7.507319e+09,1.277380e+09,-4.748494e+09,945854000.0,2.718238e+09,4.265561e+09

In [29]:
small_data_table.columns

Index(['company_id', 'name_latest', 'LiabilitiesAndStockholdersEquity',
       'Assets', 'StockholdersEquity', 'RetainedEarningsAccumulatedDeficit',
       'NetIncomeLoss', 'CashAndCashEquivalentsAtCarryingValue',
       'CashAndCashEquivalentsPeriodIncreaseDecrease',
       'CommonStockSharesAuthorized', 'CommonStockValue',
       'CommonStockSharesIssued', 'PropertyPlantAndEquipmentNet',
       'CommonStockParOrStatedValuePerShare', 'Liabilities',
       'IncomeTaxExpenseBenefit', 'AssetsCurrent', 'LiabilitiesCurrent',
       'OperatingIncomeLoss', 'CommonStockSharesOutstanding',
       'AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment',
       'PropertyPlantAndEquipmentGross'],
      dtype='object')

In [30]:
yahoo_features = (small_data_table[small_data_table['name_latest'].str.contains('Yahoo Inc')].values)[0][2:]

In [33]:
np.argsort(((small_data_table.values[:,2:]-yahoo_features)**2).mean(axis=1))

array([ 23, 776,  41, 570, 144, 714,  98, 220, 180, 876, 836, 781, 775,
       766, 909, 755, 615, 235, 924, 311, 794, 747, 723, 892, 890, 687,
       900, 638, 106, 831, 848, 181, 736, 782, 808, 196, 718, 703, 552,
       330, 405, 225, 114, 293, 614, 167, 681, 869, 148, 319, 223, 252,
       762, 348, 592, 710, 283,  82, 329, 722, 298, 744, 127, 737, 559,
       941,  25, 626, 525,  64, 445, 464, 843, 644, 787, 105,  37, 432,
       700,   7, 491, 506, 601, 664, 288, 331,  60, 760, 565, 853, 449,
       789, 802, 672, 696, 864, 142, 419, 583, 692,  18, 779, 769,  84,
       712, 640, 754, 163,  88, 680, 758, 679, 130, 101, 708, 858, 895,
       835, 373, 929, 788, 125, 806, 616, 623, 458, 442,  50, 684, 657,
       536, 857, 607, 189, 940, 155,  85, 327, 945, 825, 207, 415, 938,
       752, 891, 232,  11, 111, 394, 914, 437, 465, 425, 751, 308, 332,
       656, 702, 295, 645, 923, 852, 627, 361,  54, 342, 768, 824, 468,
       569, 104, 178, 613, 715, 486, 916, 166, 109, 778, 925, 186,  30,
       881, 898, 635, 774, 920, 711, 563, 236, 277, 743, 147,  22, 276,
       397, 772, 187, 138, 365, 199,  62, 717, 673, 880, 273, 670, 667,
       677, 919, 208,  68, 184, 800, 922, 643, 233, 603,  24, 256, 865,
       761, 378, 801, 113, 795, 489,   0, 272, 287, 786, 699,  66, 116,
       745, 863, 630, 119, 674, 521, 210, 349, 161, 720, 913, 882, 816,
       651, 561, 566, 192, 334, 218, 340, 328, 793, 427, 204, 146, 159,
       377, 598, 599, 303, 845, 173, 268, 164, 866, 931, 578, 885, 480,
       238, 564, 935, 395, 809, 250,  65,  31,  80,  77,  79,  72,  73,
        74,  78,  75,  76, 872, 915, 263, 531, 231, 589, 777, 302,  33,
        26, 282, 307, 209, 548,  89, 471, 554, 286, 942, 508, 170, 379,
        61, 316, 128, 499, 546, 686, 875, 797,  90, 306, 266,  28, 575,
        42, 153, 364, 392, 849,  51, 408, 467, 556, 537, 907, 926,   9,
       117, 558, 389, 629, 325, 317, 728, 678, 810, 572, 648, 893, 241,
       738, 474, 279, 596, 721,  19, 136, 851, 483, 840, 560,  32, 820,
       582, 847, 873, 725, 666, 103,  49, 741, 434, 315, 887, 269, 874,
       341, 438, 902, 944, 253, 463, 642, 822, 227, 503, 523, 140, 934,
       304, 258, 291, 716, 799, 894,  99,  57, 943, 883, 309,  12, 911,
       846, 588, 482, 383, 811, 515, 352,   1, 299, 381, 896, 538, 124,
       254, 426, 312, 550, 518, 157, 492, 175, 571, 202, 126, 122, 165,
       422, 179, 497, 609, 453, 821, 918, 785, 229, 243,  10, 271, 409,
       203, 284,  91, 191, 366,   2, 134, 669, 168,  47, 577, 347,  44,
        27,  71, 520, 264, 132, 493, 641, 574, 436, 494, 292, 380, 830,
       732, 884, 539, 501, 456, 150, 141, 899, 219, 335, 107, 275,  95,
       367, 647, 185,   4, 469, 237, 543, 152, 839, 242, 495, 337, 174,
       625, 921, 411, 417, 682, 473, 731,  29, 527, 145, 285, 255, 587,
       430, 593, 585, 234, 844,  52, 120, 354, 734, 188, 416, 646, 359,
       850, 440, 886, 928, 620, 171, 123, 541, 313,  15,  87, 649,   3,
       868, 451, 401, 358, 530, 608,  53, 350, 814, 632, 567, 628, 540,
       522, 197, 398, 338, 193, 510, 454, 862, 807, 879, 697, 622, 448,
       370, 160,  39, 756, 262, 301,  43, 698, 595, 910, 230, 532, 694,
       305, 339, 512, 529, 663, 604,  83, 215, 353, 300, 423, 833, 455,
        93, 466, 320, 658, 351, 281, 396, 542, 545, 257, 450, 553, 139,
       859,  45, 624, 639, 400, 573, 829, 889, 544, 198, 519, 730, 413,
       485, 461, 505,  40, 247, 498, 618, 195, 477, 605,  21, 753, 652,
       584, 346, 709, 441, 878, 650, 446, 472, 487, 691, 855, 260, 653,
       590, 206, 211, 310, 214, 336, 739, 420, 861, 135, 194, 240, 323,
       912, 665, 668, 131, 108,  36, 278, 804, 110, 183, 815, 172, 133,
       659, 296, 431, 443, 502, 513, 784, 906, 780, 100, 435, 534,  20,
       176, 511, 823, 201, 838, 322, 713, 597, 860, 404, 897, 244, 701,
       516, 819, 382, 727, 439, 129, 947, 102, 854, 535, 719, 606, 158,
       827, 221, 452, 936, 251, 418, 385, 265, 771, 676, 939, 524, 388,
       239, 496, 695, 528, 735, 514, 690, 470, 360, 274, 412, 783, 481,
       488,  96, 748, 685, 818, 228, 661, 726, 321, 917, 834, 904, 555,
       297, 362,  59, 267, 693, 424, 363, 581, 660, 576, 724, 631,  94,
       517,  92,   8,   6, 355, 374, 908, 704, 115, 259, 617,  16, 612,
       764, 602, 841, 248,  97, 767, 406, 177, 551, 579, 905, 792, 856,
       812, 901, 805,  69, 475,  81, 245, 932, 399, 828, 707,  14, 557,
       205, 403, 507, 479, 798, 742, 324, 757, 654,  67, 749, 387, 156,
       870, 270, 633,  86,  46, 345, 837, 314, 249, 637, 903, 429, 611,
       688,  55,  38, 937, 190, 457, 294, 393, 151, 791, 386, 280, 344,
       500, 504, 372, 484, 391, 591, 169, 580, 368, 326, 137, 636, 763,
       224, 390, 402, 216, 842, 933, 770, 290, 343, 414, 476, 261, 121,
       813, 217, 610, 729, 112, 421, 375,   5, 369, 212, 817, 586, 796,
       803, 832, 689, 246, 562, 621, 568,  13,  58, 222, 376, 750, 447,
       384, 371, 946, 733, 407, 594, 549, 149, 154, 213, 826, 927, 333,
       428, 182, 526, 410, 162, 930, 226, 318, 634, 289, 356, 877, 509,
       118, 773, 143, 200,  63, 444, 533, 460, 490, 867, 433, 765, 871,
        48, 759, 662, 675, 671, 478, 706,  70, 547,  34, 746,  56, 683,
       459, 619, 462,  35, 888, 790, 705, 740, 357,  17, 600, 655])

In [34]:
small_data_table.iloc[776]

company_id                                                                      790070
name_latest                                                                   EMC Corp
LiabilitiesAndStockholdersEquity                                            4.6612e+10
Assets                                                                      4.6612e+10
StockholdersEquity                                                           2.114e+10
RetainedEarningsAccumulatedDeficit                                            2.17e+10
NetIncomeLoss                                                                 1.99e+09
CashAndCashEquivalentsAtCarryingValue                                        6.549e+09
CashAndCashEquivalentsPeriodIncreaseDecrease                                  2.06e+08
CommonStockSharesAuthorized                                                      6e+09
CommonStockValue                                                               1.9e+07
CommonStockSharesIssued                                                      1.943e+09
PropertyPlantAndEquipmentNet                                                  3.85e+09
CommonStockParOrStatedValuePerShare                                               0.01
Liabilities                                                                 2.3893e+10
IncomeTaxExpenseBenefit                                                        7.1e+08
AssetsCurrent                                                               1.5063e+10
LiabilitiesCurrent                                                          1.2885e+10
OperatingIncomeLoss                                                          2.841e+09
CommonStockSharesOutstanding                                                 1.943e+09
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment     6.438e+09
PropertyPlantAndEquipmentGross                                              1.0288e+10
Name: 776, dtype: object

In [35]:
small_data_table.iloc[23]

company_id                                                                      1011006
name_latest                                                                   Yahoo Inc
LiabilitiesAndStockholdersEquity                                             4.5204e+10
Assets                                                                       4.5204e+10
StockholdersEquity                                                          2.90435e+10
RetainedEarningsAccumulatedDeficit                                          4.57081e+09
NetIncomeLoss                                                              -4.35908e+09
CashAndCashEquivalentsAtCarryingValue                                       1.63191e+09
CashAndCashEquivalentsPeriodIncreaseDecrease                               -1.03219e+09
CommonStockSharesAuthorized                                                       5e+09
CommonStockValue                                                                 959000
CommonStockSharesIssued                                                     9.62959e+08
PropertyPlantAndEquipmentNet                                                1.54732e+09
CommonStockParOrStatedValuePerShare                                               0.001
Liabilities                                                                 1.61245e+10
IncomeTaxExpenseBenefit                                                     -8.9598e+07
AssetsCurrent                                                               7.50732e+09
LiabilitiesCurrent                                                          1.27738e+09
OperatingIncomeLoss                                                        -4.74849e+09
CommonStockSharesOutstanding                                                9.45854e+08
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    2.71824e+09
PropertyPlantAndEquipmentGross                                              4.26556e+09
Name: 23, dtype: object

# Three strategies for dealing with missing data

1. One thing we could do is drop any row that has any missing values. We did this above.
2. We could replace any missing value with zero.
3. We could replace any missing value with the mean or median.

Lets replace with zero and see what happens.

In [41]:
company_features_df_zero = pivot_df[pop_ind].copy()

In [42]:
company_features_df_zero.shape

(9619, 20)

In [43]:
company_features_df_zero.isnull().any()

indicator_id
LiabilitiesAndStockholdersEquity                                            True
Assets                                                                      True
StockholdersEquity                                                          True
RetainedEarningsAccumulatedDeficit                                          True
NetIncomeLoss                                                               True
CashAndCashEquivalentsAtCarryingValue                                       True
CashAndCashEquivalentsPeriodIncreaseDecrease                                True
CommonStockSharesAuthorized                                                 True
CommonStockValue                                                            True
CommonStockSharesIssued                                                     True
PropertyPlantAndEquipmentNet                                                True
CommonStockParOrStatedValuePerShare                                         True
Liabilities                                                                 True
IncomeTaxExpenseBenefit                                                     True
AssetsCurrent                                                               True
LiabilitiesCurrent                                                          True
OperatingIncomeLoss                                                         True
CommonStockSharesOutstanding                                                True
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    True
PropertyPlantAndEquipmentGross                                              True
dtype: bool

There are nulls everywhere.

In [44]:
company_features_df_zero.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9619 entries, 1750 to 1666114
Data columns (total 20 columns):
LiabilitiesAndStockholdersEquity                                            6012 non-null float64
Assets                                                                      5997 non-null float64
StockholdersEquity                                                          5503 non-null float64
RetainedEarningsAccumulatedDeficit                                          5500 non-null float64
NetIncomeLoss                                                               5492 non-null float64
CashAndCashEquivalentsAtCarryingValue                                       5490 non-null float64
CashAndCashEquivalentsPeriodIncreaseDecrease                                5151 non-null float64
CommonStockSharesAuthorized                                                 5114 non-null float64
CommonStockValue                                                            4916 non-null float64
CommonStockSharesIssued                                                     4901 non-null float64
PropertyPlantAndEquipmentNet                                                4808 non-null float64
CommonStockParOrStatedValuePerShare                                         4763 non-null float64
Liabilities                                                                 4659 non-null float64
IncomeTaxExpenseBenefit                                                     4614 non-null float64
AssetsCurrent                                                               4598 non-null float64
LiabilitiesCurrent                                                          4597 non-null float64
OperatingIncomeLoss                                                         4522 non-null float64
CommonStockSharesOutstanding                                                4519 non-null float64
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    4519 non-null float64
PropertyPlantAndEquipmentGross                                              4192 non-null float64
dtypes: float64(20)
memory usage: 1.5 MB

Only about 6K to 4K not null. Lets fill with zeros.

In [45]:
company_features_df_zero.fillna(0,inplace=True)

In [46]:
company_features_df_zero.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9619 entries, 1750 to 1666114
Data columns (total 20 columns):
LiabilitiesAndStockholdersEquity                                            9619 non-null float64
Assets                                                                      9619 non-null float64
StockholdersEquity                                                          9619 non-null float64
RetainedEarningsAccumulatedDeficit                                          9619 non-null float64
NetIncomeLoss                                                               9619 non-null float64
CashAndCashEquivalentsAtCarryingValue                                       9619 non-null float64
CashAndCashEquivalentsPeriodIncreaseDecrease                                9619 non-null float64
CommonStockSharesAuthorized                                                 9619 non-null float64
CommonStockValue                                                            9619 non-null float64
CommonStockSharesIssued                                                     9619 non-null float64
PropertyPlantAndEquipmentNet                                                9619 non-null float64
CommonStockParOrStatedValuePerShare                                         9619 non-null float64
Liabilities                                                                 9619 non-null float64
IncomeTaxExpenseBenefit                                                     9619 non-null float64
AssetsCurrent                                                               9619 non-null float64
LiabilitiesCurrent                                                          9619 non-null float64
OperatingIncomeLoss                                                         9619 non-null float64
CommonStockSharesOutstanding                                                9619 non-null float64
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    9619 non-null float64
PropertyPlantAndEquipmentGross                                              9619 non-null float64
dtypes: float64(20)
memory usage: 1.5 MB

All non-zero now. Unfortunatly we might care that we just changed the means:

In [48]:
 pivot_df[pop_ind].mean(axis=0)

indicator_id
LiabilitiesAndStockholdersEquity                                            9.350417e+09
Assets                                                                      9.114170e+09
StockholdersEquity                                                          1.843766e+09
RetainedEarningsAccumulatedDeficit                                          1.089772e+09
NetIncomeLoss                                                               1.746629e+08
CashAndCashEquivalentsAtCarryingValue                                       3.653578e+08
CashAndCashEquivalentsPeriodIncreaseDecrease                                1.150354e+07
CommonStockSharesAuthorized                                                 5.118975e+08
CommonStockValue                                                            1.207619e+08
CommonStockSharesIssued                                                     1.622055e+08
PropertyPlantAndEquipmentNet                                                1.757120e+09
CommonStockParOrStatedValuePerShare                                         9.450877e+01
Liabilities                                                                 8.126974e+09
IncomeTaxExpenseBenefit                                                     9.185107e+07
AssetsCurrent                                                               1.195995e+09
LiabilitiesCurrent                                                          8.754635e+08
OperatingIncomeLoss                                                         2.805663e+08
CommonStockSharesOutstanding                                                1.595832e+08
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    1.154240e+09
PropertyPlantAndEquipmentGross                                              2.868405e+09
dtype: float64

In [49]:
company_features_df_zero.mean(axis=0)

indicator_id
LiabilitiesAndStockholdersEquity                                            5.844132e+09
Assets                                                                      5.682262e+09
StockholdersEquity                                                          1.054813e+09
RetainedEarningsAccumulatedDeficit                                          6.231151e+08
NetIncomeLoss                                                               9.972434e+07
CashAndCashEquivalentsAtCarryingValue                                       2.085263e+08
CashAndCashEquivalentsPeriodIncreaseDecrease                                6.160175e+06
CommonStockSharesAuthorized                                                 2.721534e+08
CommonStockValue                                                            6.171801e+07
CommonStockSharesIssued                                                     8.264573e+07
PropertyPlantAndEquipmentNet                                                8.782862e+08
CommonStockParOrStatedValuePerShare                                         4.679751e+01
Liabilities                                                                 3.936331e+09
IncomeTaxExpenseBenefit                                                     4.405872e+07
AssetsCurrent                                                               5.717001e+08
LiabilitiesCurrent                                                          4.183913e+08
OperatingIncomeLoss                                                         1.318974e+08
CommonStockSharesOutstanding                                                7.497207e+07
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    5.422611e+08
PropertyPlantAndEquipmentGross                                              1.250063e+09
dtype: float64

Instead lets use the means to fill in the values and see what happens then.

In [50]:
company_features_df_mean_fill = pivot_df[pop_ind].copy()

In [55]:
fill_values = dict(zip(pop_ind,pivot_df[pop_ind].mean(axis=0).values))

In [56]:
company_features_df_mean_fill.fillna(fill_values, inplace=True)

In [57]:
company_features_df_mean_fill.mean(axis=0)

indicator_id
LiabilitiesAndStockholdersEquity                                            9.350417e+09
Assets                                                                      9.114170e+09
StockholdersEquity                                                          1.843766e+09
RetainedEarningsAccumulatedDeficit                                          1.089772e+09
NetIncomeLoss                                                               1.746629e+08
CashAndCashEquivalentsAtCarryingValue                                       3.653578e+08
CashAndCashEquivalentsPeriodIncreaseDecrease                                1.150354e+07
CommonStockSharesAuthorized                                                 5.118975e+08
CommonStockValue                                                            1.207619e+08
CommonStockSharesIssued                                                     1.622055e+08
PropertyPlantAndEquipmentNet                                                1.757120e+09
CommonStockParOrStatedValuePerShare                                         9.450877e+01
Liabilities                                                                 8.126974e+09
IncomeTaxExpenseBenefit                                                     9.185107e+07
AssetsCurrent                                                               1.195995e+09
LiabilitiesCurrent                                                          8.754635e+08
OperatingIncomeLoss                                                         2.805663e+08
CommonStockSharesOutstanding                                                1.595832e+08
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    1.154240e+09
PropertyPlantAndEquipmentGross                                              2.868405e+09
dtype: float64

In [58]:
company_features_df_mean_fill.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9619 entries, 1750 to 1666114
Data columns (total 20 columns):
LiabilitiesAndStockholdersEquity                                            9619 non-null float64
Assets                                                                      9619 non-null float64
StockholdersEquity                                                          9619 non-null float64
RetainedEarningsAccumulatedDeficit                                          9619 non-null float64
NetIncomeLoss                                                               9619 non-null float64
CashAndCashEquivalentsAtCarryingValue                                       9619 non-null float64
CashAndCashEquivalentsPeriodIncreaseDecrease                                9619 non-null float64
CommonStockSharesAuthorized                                                 9619 non-null float64
CommonStockValue                                                            9619 non-null float64
CommonStockSharesIssued                                                     9619 non-null float64
PropertyPlantAndEquipmentNet                                                9619 non-null float64
CommonStockParOrStatedValuePerShare                                         9619 non-null float64
Liabilities                                                                 9619 non-null float64
IncomeTaxExpenseBenefit                                                     9619 non-null float64
AssetsCurrent                                                               9619 non-null float64
LiabilitiesCurrent                                                          9619 non-null float64
OperatingIncomeLoss                                                         9619 non-null float64
CommonStockSharesOutstanding                                                9619 non-null float64
AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment    9619 non-null float64
PropertyPlantAndEquipmentGross                                              9619 non-null float64
dtypes: float64(20)
memory usage: 1.5 MB

So here we replace the missing value with the mean of that attribute. In this way the mean of the attirbute over the data does not change.